fonts = [
		("cooleyshapesquareendsregular", "https://2ttf.com/webfont/3uPTAlcKj2s/webfont.ttf"),
		("cooleyshapesemiformal", "https://2ttf.com/webfont/LC6k3RADFA6/webfont.ttf"),
		("cooleyshapesquareendsregularnormalizedwidth", "https://2ttf.com/webfont/3uPTAlcKj2s/webfont.ttf"),
		("Cooley shape informal", "./fonts/Cooleyshapeinformal.ttf"),
		("cooleyshapes", "https://2ttf.com/webfont/2Y1pWHUySSg/webfont.ttf"),
		("cooleytrampoline", "https://2ttf.com/webfont/H0sclMuwL2Y/webfont.ttf"),
		("cooleycatface", "https://2ttf.com/webfont/IVXDjFMrdQw/webfont.ttf"),
		("cooley unstruktured", "https://2ttf.com/webfont/Aor4JCozEOg/webfont.ttf"),
		("cooley revival", "https://2ttf.com/webfont/8UwzXEt8vQa/webfont.ttf"),
		("cooley moar cats", "https://2ttf.com/webfont/SH3UvTMR/webfont.ttf"),
		("cooley free backwards font", "https://2ttf.com/webfont/T2o5sC45/webfont.ttf"),
		("cooley middle airplane seat", "https://2ttf.com/webfont/Vp4maQl8/webfont.ttf"),
		("cooley ananas wacky", "https://2ttf.com/webfont/PaM4icff/webfont.ttf"),
		("cooley masking tape block", "https://2ttf.com/webfont/ZJ8MQrlU/webfont.ttf"),
		("cooley questionable sans", "https://2ttf.com/webfont/M7AcbTKB/webfont.ttf"),
		# ("cooley RAWR!", "./fonts/Rawr.ttf"),
		("cooley inverted", "https://2ttf.com/webfont/dYBCdZet/webfont.ttf"),
		("cooley robot arms", "https://2ttf.com/webfont/Offsosp1/webfont.ttf"),
		("cooley chunk", "https://2ttf.com/webfont/VzIgBSZN/webfont.ttf"),
		("cooley urban scrawl", "https://2ttf.com/webfont/YxZbQTxX/webfont.ttf"),
		("cooley draftsmanship", "https://2ttf.com/webfont/cHZhXK3K/webfont.ttf"),
		("cooley slowball", "https://2ttf.com/webfont/UXvcscNC/webfont.ttf"),
		("cooley greeting card serif", "https://2ttf.com/webfont/PHTFSxpW/webfont.ttf"),
		("cooley greeting card sans", "https://2ttf.com/webfont/QaGnHdxY/webfont.ttf"),
		("cooley inconsistent double", "https://2ttf.com/webfont/bGU3UYgG/webfont.ttf"),
		("cooley bloop", "./fonts/cooleybloop.ttf"),
		("cooley cats", "https://2ttf.com/webfont/WilTfliz/webfont.ttf"),
		("cooley casual", "https://2ttf.com/webfont/VRbITUwo/webfont.ttf"),
		("cooley caltrain", "./fonts/caltrain.ttf"),
		("cooley robotfaces", "./fonts/Cooley_robotfaces01.ttf"),
		("cooley cats02", "./fonts/Cooleycats02.ttf"),
		("cooley Galaxina", "./fonts/Galaxina.ttf"),
		("cooley KboyFont", "./fonts/KboyFont.ttf"),
		("cooley Magneato", "./fonts/Magneato.ttf"),
		("cooley netlabel square ends", "./fonts/netlabel_square_ends.ttf"),
		# ("cooley pew! pew! pew!", "./fonts/pew!-pew!-pew!.woff2"),
		("cooley Redneck Astronaut", "./fonts/Redneck_Astronaut.ttf"),
		("cooley stevecooley", "./fonts/Stevecooley.ttf"),
		("cooley Tamestyle", "./fonts/Tamestyle.ttf"),
		("cooley whitespace_is_evil", "./fonts/whitespace_is_evil.ttf"),
	]